### ISSUE TITLE
Options for character encoding (Suggestion)

### ISSUE THREAD

**Issue by mo-op** [rtbigdata/shp-mongo-import.py#1]
I had issues with encoding latin characters, hence had to tweak the script with an extra loop to iterate through the values:

` value = unicode(value, 'latin-1')`

Adding such checks would be helpful!

**Comment by rtbigdata** [comment]
Thank you, Manasa.  That's a good catch!  I created this for a personal project and decided to share it on github.  Always interested in improvements that would make this useful to others.  Are you interested in doing a pull request to add your Unicode check?

Kind regards,
Rick


----- Reply message -----

**Comment by mo-op** [comment]
Sure, that sounds neat. :) Will work on it.

**Comment by mo-op** [comment]
Sure, that sounds neat. :) Will work on it.
